// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ObjCRuntime;

namespace AccessoryTextInput
{
	public partial class TextInputObject : UITextField
	{
		private InputView _inputView;

		public TextInputObject (IntPtr handle) : base (handle)
		{
		}

		public TextInputObject()
		{			
			var arr = NSBundle.MainBundle.LoadNib ("InputView", null, null);
			_inputView = Runtime.GetNSObject<InputView> (arr.ValueAt(0));
			_inputView.TranslatesAutoresizingMaskIntoConstraints = false;
			_inputView.pubTextView.Changed += (object sender, EventArgs e) => BecomeFirstResponder();

			_inputView.AddConstraint (NSLayoutConstraint.Create (_inputView,
				NSLayoutAttribute.Height,
				NSLayoutRelation.GreaterThanOrEqual,
				null,
				NSLayoutAttribute.NoAttribute,
				0, 44));

			_inputView.AddConstraint (NSLayoutConstraint.Create (_inputView,
				NSLayoutAttribute.Height,
				NSLayoutRelation.LessThanOrEqual,
				null,
				NSLayoutAttribute.NoAttribute,
				0, 128));


			InputAccessoryView = _inputView;
		}

		public override bool BecomeFirstResponder ()
		{
			base.BecomeFirstResponder ();
			_inputView.BecomeFirstResponder ();

			var cons = _inputView.InputAccessoryView.Superview.Constraints;
			InputAccessoryView.Superview.RemoveConstraint (cons [0]);
			return true;
		}

		public override bool ResignFirstResponder ()
		{
			_inputView.ResignFirstResponder ();
			base.ResignFirstResponder ();
			return true;
		}
	}
}
