// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AccessoryTextInput
{
	public partial class InputView : UIView
	{
		public InputView (IntPtr handle) : base (handle)
		{
		}

		public override bool BecomeFirstResponder ()
		{
			return TextView.BecomeFirstResponder ();
		}
	}
}
