// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AccessoryTextInput
{
	public partial class InputView : UIView
	{
		public InputView (IntPtr handle) : base (handle)
		{
		}



		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();
			TextField.TranslatesAutoresizingMaskIntoConstraints = true;

			TextView.Changed += (object sender, EventArgs e) => {
				var test = TextField.TranslatesAutoresizingMaskIntoConstraints;

				if (TextView.ContentSize.Height >= 128 - 16) {
					TextView.ScrollEnabled = true;
				} else {
					if (TextView.ScrollEnabled) {
						TextView.ScrollEnabled = false;
						TextView.SizeToFit();
					}
				}
			};
		}

		public override void LayoutSubviews ()
		{
			base.LayoutSubviews ();
			TextField.Frame = TextView.Frame;
		}

		public override bool BecomeFirstResponder ()
		{
			return TextView.BecomeFirstResponder ();
		}
	}
}
