// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ObjCRuntime;

namespace AccessoryTextInput
{
	public partial class TextInputObject : UITextField
	{
		private InputView _inputView;
		private Action<string> _callback;
		private string _hint;
		private bool _didRotate = false;
		private NSLayoutConstraint _maxHeightConstraint;

		private nfloat _maxHeight = 128.0f;
		public nfloat MaxHeight { 
			get { return _maxHeight; }
			set { _maxHeight = value; _maxHeightConstraint.Constant = value; } 
		}

		public TextInputObject()
		{			
			var arr = NSBundle.MainBundle.LoadNib ("InputView", null, null);
			_inputView = Runtime.GetNSObject<InputView> (arr.ValueAt(0));
			_inputView.TranslatesAutoresizingMaskIntoConstraints = false;

			_inputView.TextView.Changed += TextView_Changed;
			_inputView.DoneButton.TouchUpInside += DoneButton_TouchUpInside;

			SetConstraints ();
			InputAccessoryView = _inputView;
		}

		public void GetInput(string hint, string initialText, Action<string> callback)
		{
			_inputView.TextView.Text = initialText;
			_callback = callback;
			_hint = hint;
			SetHint ();
			DisableScrolling (); // Disable scrolling when the input is shown. It could still be on from the last usage
			BecomeFirstResponder ();
		}

		public void Cancel() {
			_callback = null;
			ResignFirstResponder ();
		}

		public override bool BecomeFirstResponder ()
		{
			base.BecomeFirstResponder ();
			_inputView.TextView.BecomeFirstResponder ();

			//HACK - iOS adds a height constraint which prevents the UITextView from expanding so we remove it manually.
			//		 Probably ought to check more carefully but currently just remove the first constraint in the array.
			var accessoryParentConstraints = _inputView.InputAccessoryView.Superview.Constraints;
			InputAccessoryView.Superview.RemoveConstraint (accessoryParentConstraints [0]);
			return true;
		}

		public override bool ResignFirstResponder ()
		{
			_inputView.TextView.ResignFirstResponder ();
			base.ResignFirstResponder ();
			return true;
		}

		public void DidRotate() 
		{
			_didRotate = true;
		}

		private void DoneButton_TouchUpInside (object sender, EventArgs e)
		{
			_callback(_inputView.TextView.Text);
			ResignFirstResponder();			
			_callback = null;
		}

		private void TextView_Changed (object sender, EventArgs e)
		{
			SetHint ();

			if (_inputView.TextView.ContentSize.Height >= MaxHeight - 16) {	// 16 is two lots of the padding top and bottom of the TextView
				_inputView.TextView.ScrollEnabled = true;
			} else if (_inputView.TextView.ScrollEnabled) {
				DisableScrolling ();
			}

			//HACK - Calling BecomeFirstResponder fixes an issue where the UITextView stops growing/shrinking after rotation.
			//		 There must be a more subtle solution that is being triggered by BecomeFirstResponder but less heavy handed.
			//		 Also this stops the user holding down delete. So need a proper solution!
			//BecomeFirstResponder ();

			//HACK - Changed the hack so it only happens if the containing View Controller alerts the TextInputObject of a rotation. 
			//		 Annoying extra code in the ViewController but at least everything is working nicely.
			if (_didRotate) {
				BecomeFirstResponder ();
				_didRotate = false;
			}
		}

		private void SetHint() {
			if (string.IsNullOrEmpty (_inputView.TextView.Text)) {
				_inputView.TextField.Placeholder = _hint;
			} else {
				_inputView.TextField.Placeholder = null;
			}
		}

		private void DisableScrolling()
		{
			_inputView.TextView.ScrollEnabled = false;
			_inputView.TextView.SizeToFit ();
		}

		private void SetConstraints() {
			_maxHeightConstraint = NSLayoutConstraint.Create (_inputView,
				NSLayoutAttribute.Height,
				NSLayoutRelation.LessThanOrEqual,
				null,
				NSLayoutAttribute.NoAttribute,
				0, MaxHeight);


			var minHeightConstraint = NSLayoutConstraint.Create (_inputView,
				NSLayoutAttribute.Height,
				NSLayoutRelation.GreaterThanOrEqual,
				null,
				NSLayoutAttribute.NoAttribute,
				0, 44);

			_inputView.AddConstraint (_maxHeightConstraint);
			_inputView.AddConstraint (minHeightConstraint);
		}
	}
}
