// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ObjCRuntime;

namespace AccessoryTextInput
{
	public partial class TextInputObject : UITextField
	{
		private InputView _inputView;
		private Action<string> _callback;

		public TextInputObject()
		{			
			var arr = NSBundle.MainBundle.LoadNib ("InputView", null, null);
			_inputView = Runtime.GetNSObject<InputView> (arr.ValueAt(0));
			_inputView.TranslatesAutoresizingMaskIntoConstraints = false;

			_inputView.TextView.Changed += TextView_Changed;
			_inputView.DoneButton.TouchUpInside += DoneButton_TouchUpInside;

			_inputView.AddConstraint (NSLayoutConstraint.Create (_inputView,
				NSLayoutAttribute.Height,
				NSLayoutRelation.GreaterThanOrEqual,
				null,
				NSLayoutAttribute.NoAttribute,
				0, 44));

			_inputView.AddConstraint (NSLayoutConstraint.Create (_inputView,
				NSLayoutAttribute.Height,
				NSLayoutRelation.LessThanOrEqual,
				null,
				NSLayoutAttribute.NoAttribute,
				0, 128));
			
			InputAccessoryView = _inputView;
		}

		public void GetInput(string initialText, Action<string> callback)
		{
			_callback = callback;
			_inputView.TextView.Text = initialText;
			BecomeFirstResponder ();
		}

		public void Cancel() {
			ResignFirstResponder ();
		}

		public override bool BecomeFirstResponder ()
		{
			base.BecomeFirstResponder ();
			_inputView.TextView.BecomeFirstResponder ();

			var cons = _inputView.InputAccessoryView.Superview.Constraints;
			InputAccessoryView.Superview.RemoveConstraint (cons [0]);
			return true;
		}

		public override bool ResignFirstResponder ()
		{
			_inputView.TextView.ResignFirstResponder ();
			base.ResignFirstResponder ();
			return true;
		}

		private void DoneButton_TouchUpInside (object sender, EventArgs e)
		{
			_callback(_inputView.TextView.Text);
			ResignFirstResponder();			
		}

		private void TextView_Changed (object sender, EventArgs e)
		{
			BecomeFirstResponder ();

			if (_inputView.TextView.ContentSize.Height >= 128 - 16) {
				_inputView.TextView.ScrollEnabled = true;
			} else {
				if (_inputView.TextView.ScrollEnabled) {
					_inputView.TextView.ScrollEnabled = false;
					_inputView.TextView.SizeToFit ();
				}
			}
		}
	}
}
